### ISSUE TITLE
Compiling on Raspberry Pi

### ISSUE THREAD

**Issue by alwint3r** [pisontechnology/nrf52-desktop-dfu#7]
Hello,

I tried to compile this tool on a Raspbery Pi 3 Model B+ (ARM Cortex-A53 processor) and failed at linking libnativeble-static.a with the following error:

```
[ 23%] Built target dfu-static
[ 30%] Linking CXX executable ../../bin/linux/dfu_app
/usr/bin/ld: ../../src-dfu-app/ble/linux/libnativeble-static.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/dfu_app.dir/build.make:161: ../../bin/linux/dfu_app] Error 1
make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/dfu_app.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

I am willing to compile the libnativeble-static as well, but I can't find the source anywhere. I assume that it is a closed-source software.

Is there any way to fix this?

Thanks

**Comment by Sir-Branch** [comment]
Hi thanks for reaching out!

I suspect the issue with linkage is due to the processor type of the Raspberry Pi (Cortex-A53), I ran into similar issues when trying to install nRF connect on a Cortex-A7 (Model 2B). The .lib is probably built for a x86 core (I might be completely wrong). Static compilation/linkage is probably best 

The latest version of that library can be found https://github.com/kdewald/nativeble, Kevin has recently deprecated it in favor of SimpleBLE but it should still be functional. 

If you have any issues please feel free to reach out, I'm happy to help :smile:

**Comment by alwint3r** [comment]
Hi @Sir-Branch

It's good to know that the source code is available. Thanks! I'll try that out.

**Comment by alwint3r** [comment]
Closing this issue as the problem is solved. Thanks for your help @Sir-Branch!
